### ISSUE TITLE
SystemJS error when import HttpClient 

### ISSUE THREAD

**Issue by aGoncharuks** [mgechev/angular-seed#2046] opened 2017-08-09 07:20 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
SystemJS error when import HttpClient

**Expected behavior**
No error

**Minimal reproduction of the problem with instructions**
Hi. I'm experiencing problems with adding new HttpClient to SystemJS in Angular seed. I've read comments here https://github.com/mgechev/angular-seed/issues/2033, but offered solutions didn't help. What I've done so far:
1. npm install tslib --save-dev
2. add these to packages to additionalPackages in tools/config/project.config.ts (as mentioned in 
@maxklenk comment in issue 2033):
```      {
        name: '@angular/common/http',
        path: 'node_modules/@angular/common',
        packageMeta: {
          main: 'bundles/common-http.umd.js',
          defaultExtension: 'js'
        }
      },
      {
        name: 'tslib',
        path: 'node_modules/tslib',
        packageMeta: {
          main: 'tslib.js',
          defaultExtension: 'js'
        }
      }
```
3. add HttpClientModule import to app.module.ts

And I get this error as result: http://imgur.com/a/ZoYYW

I did these steps afterwards:
- delete node modules folder
- npm cache clean
- npm install 

And still have the same error when run "npm start".
Angular version: 4.3.1

**Comment by negberts** [comment] 2017-08-10 09:46
I've added `'@angular/common/http': 'node_modules/@angular/common/bundles/common-http.umd.js',` to both SYSTEM_CONFIG_DEV and SYSTEM_BUILDER_CONFIG in seed.config.ts and tslib via additionalpackages in project.config.ts with

```
{
                name: 'tslib',
                path: 'node_modules/tslib/tslib.js'
            }
```

**Comment by pankajparkar** [comment] 2017-08-11 12:10
Extending @negberts  comments, It additionally needs `tslib` because `@angular/common/http` is dependant on `tslib`, see [Source Here](https://github.com/angular/common-builds/blob/4.3.0/bundles/common-http.umd.js#L7)

**Comment by aGoncharuks** [comment] 2017-08-17 11:19
@negberts  do it get it right that to get http client working you did the following steps:
1. In seed.config.ts:
 Add this line of code:
` '@angular/common/http': 'node_modules/@angular/common/bundles/common-http.umd.js' `
to SYSTEM_CONFIG_DEV.paths object and to SYSTEM_BUILDER_CONFIG.paths
2. In project.config.ts add this package definition to additionalPackages array:
``` 
{
      name: 'tslib',
      path: 'node_modules/tslib/tslib.js'
} 
 ```
3. In app.module.ts:
Add HttpClientModule to IMPORTS array and import the module like this:
` import { HttpClientModule } from '@angular/common/http';  `

And it worked for you with no errors. 
Are there any steps I missed?

**Comment by negberts** [comment] 2017-08-17 11:21
Nope. That works for us.

**Comment by aGoncharuks** [comment] 2017-08-17 12:01
@negberts did the same in our project, doesn't work for us for some reason. Neither works solution in offered in #2033, which is different from yours. 
Is there a way for me to see your seed.config.ts file? I believe your repository is private, but maybe you can share this config while which shouldn't contain any confidential code.

**Comment by negberts** [comment] 2017-08-17 12:05
```
/**
     * The configuration of SystemJS for the `dev` environment.
     * @type {any}
     */
    SYSTEM_CONFIG_DEV: any = {
        meta: {
            'xlsx': {
                exports: 'XLSX' // <-- this is needed to tell SystemJS to expose XLSX
            }
        },
        paths: {
            [this.BOOTSTRAP_MODULE]: `${this.APP_BASE}${this.BOOTSTRAP_MODULE}`,
            [this.BOOTSTRAP_DEV_MODULE]: `${this.APP_BASE}${this.BOOTSTRAP_DEV_MODULE}`,
            '@angular/animations': 'node_modules/@angular/animations/bundles/animations.umd.js',
            '@angular/animations/browser': 'node_modules/@angular/animations/bundles/animations-browser.umd.js',
            '@angular/platform-browser/animations':
            'node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js',
            '@angular/common': 'node_modules/@angular/common/bundles/common.umd.js',
            '@angular/common/http': 'node_modules/@angular/common/bundles/common-http.umd.js',
            '@angular/compiler': 'node_modules/@angular/compiler/bundles/compiler.umd.js',
            '@angular/core': 'node_modules/@angular/core/bundles/core.umd.js',
            '@angular/forms': 'node_modules/@angular/forms/bundles/forms.umd.js',
            '@angular/http': 'node_modules/@angular/http/bundles/http.umd.js',
            '@angular/platform-browser': 'node_modules/@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic':
            'node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/router': 'node_modules/@angular/router/bundles/router.umd.js',
            'primeng': 'node_modules/primeng',
            'app/': `${this.APP_BASE}app/`,
            // For test config
            'dist/dev/': '/base/dist/dev/',
            '': 'node_modules/'
        },
        map: {
            'xlsx': this.BUILD_TYPE === BUILD_TYPES.PRODUCTION ? 'node_modules/xlsx/xlsx.min.js' : 'node_modules/xlsx/dist/xlsx.full.min.js',
            'fs': this.BUILD_TYPE === BUILD_TYPES.PRODUCTION ? '@node/fs' : '', // <-- systemjs doesn't seem to automatically suppress node core
            'crypto': this.BUILD_TYPE === BUILD_TYPES.PRODUCTION ? '@node/crypto' : '',
            'stream': this.BUILD_TYPE === BUILD_TYPES.PRODUCTION ? '@node/stream' : '',
            'd3-array': 'node_modules/d3-array',
            'd3-brush': 'node_modules/d3-brush',
            'd3-shape': 'node_modules/d3-shape',
            'd3-selection': 'node_modules/d3-selection',
            'd3-color': 'node_modules/d3-color',
            'd3-drag': 'node_modules/d3-drag',
            'd3-transition': 'node_modules/d3-transition',
            'd3-format': 'node_modules/d3-format',
            'd3-force': 'node_modules/d3-force',
            'd3-dispatch': 'node_modules/d3-dispatch',
            'd3-path': 'node_modules/d3-path',
            'd3-ease': 'node_modules/d3-ease',
            'd3-timer': 'node_modules/d3-timer',
            'd3-quadtree': 'node_modules/d3-quadtree',
            'd3-interpolate': 'node_modules/d3-interpolate',
            'd3-scale': 'node_modules/d3-scale',
            'd3-time': 'node_modules/d3-time',
            'd3-collection': 'node_modules/d3-collection',
            'd3-time-format': 'node_modules/d3-time-format',
            'd3-hierarchy': 'node_modules/d3-hierarchy',
            '@swimlane/ngx-charts': 'node_modules/@swimlane/ngx-charts',
        },
        packages: {
            [this.BOOTSTRAP_DIR]: {
                'defaultExtension': 'js'
            },
            'primeng': {
                'defaultExtension': 'js'
            },
            '@swimlane/ngx-charts': { main: 'release/index.min.js', defaultExtension: 'js' },
            'd3-array': { main: 'build/d3-array.min.js', defaultExtension: 'js' },
            'd3-format': { main: 'build/d3-format.min.js', defaultExtension: 'js' },
            'd3-brush': { main: 'build/d3-brush.min.js', defaultExtension: 'js' },
            'd3-color': { main: 'build/d3-color.min.js', defaultExtension: 'js' },
            'd3-force': { main: 'build/d3-force.min.js', defaultExtension: 'js' },
            'd3-hierarchy': { main: 'build/d3-hierarchy.min.js', defaultExtension: 'js' },
            'd3-interpolate': { main: 'build/d3-interpolate.min.js', defaultExtension: 'js' },
            'd3-scale': { main: 'build/d3-scale.min.js', defaultExtension: 'js' },
            'd3-selection': { main: 'build/d3-selection.min.js', defaultExtension: 'js' },
            'd3-shape': { main: 'build/d3-shape.min.js', defaultExtension: 'js' },
            'd3-time-format': { main: 'build/d3-time-format.min.js', defaultExtension: 'js' },
            'd3-drag': { main: 'build/d3-drag.min.js', defaultExtension: 'js' },
            'd3-transition': { main: 'build/d3-transition.min.js', defaultExtension: 'js' },
            'd3-dispatch': { main: 'build/d3-dispatch.min.js', defaultExtension: 'js' },
            'd3-path': { main: 'build/d3-path.min.js', defaultExtension: 'js' },
            'd3-ease': { main: 'build/d3-ease.min.js', defaultExtension: 'js' },
            'd3-timer': { main: 'build/d3-timer.min.js', defaultExtension: 'js' },
            'd3-quadtree': { main: 'build/d3-quadtree.min.js', defaultExtension: 'js' },
            'd3-time': { main: 'build/d3-time.min.js', defaultExtension: 'js' },
            'd3-collection': { main: 'build/d3-collection.min.js', defaultExtension: 'js' }
        }
    };

    /**
     * The configuration of SystemJS of the application.
     * Per default, the configuration of the `dev` environment will be used.
     * @type {any}
     */
    SYSTEM_CONFIG: any = this.SYSTEM_CONFIG_DEV;

    /**
     * The system builder configuration of the application.
     * @type {any}
     */
    SYSTEM_BUILDER_CONFIG: any = {
        //use typescript for compilation
        transpiler: 'typescript',
        //typescript compiler options
        typescriptOptions: {
            emitDecoratorMetadata: true
        },
        defaultJSExtensions: true,
        base: this.PROJECT_ROOT,
        packageConfigPaths: [
            join('node_modules', '*', 'package.json'),
            join('node_modules', '@angular', '*', 'package.json')
        ],
        meta: {
            'xlsx': {
                exports: 'XLSX' // <-- this is needed to tell SystemJS to expose XLSX
            }
        },
        map: {
            'xlsx': this.BUILD_TYPE === BUILD_TYPES.DEVELOPMENT ? 'node_modules/xlsx/xlsx.min.js' : 'node_modules/xlsx/dist/xlsx.full.min.js',
            'fs': '@node/fs',
            'crypto': '@node/crypto',
            'stream': '@node/stream',
            'd3-array': 'node_modules/d3-array',
            'd3-brush': 'node_modules/d3-brush',
            'd3-shape': 'node_modules/d3-shape',
            'd3-selection': 'node_modules/d3-selection',
            'd3-color': 'node_modules/d3-color',
            'd3-drag': 'node_modules/d3-drag',
            'd3-transition': 'node_modules/d3-transition',
            'd3-format': 'node_modules/d3-format',
            'd3-force': 'node_modules/d3-force',
            'd3-dispatch': 'node_modules/d3-dispatch',
            'd3-path': 'node_modules/d3-path',
            'd3-ease': 'node_modules/d3-ease',
            'd3-timer': 'node_modules/d3-timer',
            'd3-quadtree': 'node_modules/d3-quadtree',
            'd3-interpolate': 'node_modules/d3-interpolate',
            'd3-scale': 'node_modules/d3-scale',
            'd3-time': 'node_modules/d3-time',
            'd3-collection': 'node_modules/d3-collection',
            'd3-time-format': 'node_modules/d3-time-format',
            'd3-hierarchy': 'node_modules/d3-hierarchy',
            '@swimlane/ngx-charts': 'node_modules/@swimlane/ngx-charts',
        },
        paths: {
            // Note that for multiple apps this configuration need to be updated
            // You will have to include entries for each individual application in
            // `src/client`.
            [join(this.TMP_DIR, this.BOOTSTRAP_DIR, '*')]: `${this.TMP_DIR}/${this.BOOTSTRAP_DIR}/*`,
            '@angular/platform-browser/animations': 'node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js',
            '@angular/animations/browser': 'node_modules/@angular/animations/bundles/animations-browser.umd.js',
            '@angular/common/http': 'node_modules/@angular/common/bundles/common-http.umd.js',
            'dist/tmp/node_modules/*': 'dist/tmp/node_modules/*',
            'node_modules/*': 'node_modules/*',
            'primeng': 'node_modules/primeng',
            '*': 'node_modules/*'
        },
        packages: {
            '@angular/animations': {
                main: 'bundles/animations.umd.js',
                defaultExtension: 'js'
            },
            '@angular/platform-browser/animations': {
                main: 'bundles/platform-browser-animations.umd.js',
                defaultExtension: 'js'
            },
            '@angular/common': {
                main: 'bundles/common.umd.js',
                defaultExtension: 'js'
            },
            '@angular/compiler': {
                main: 'bundles/compiler.umd.js',
                defaultExtension: 'js'
            },
            '@angular/core': {
                main: 'bundles/core.umd.js',
                defaultExtension: 'js'
            },
            '@angular/forms': {
                main: 'bundles/forms.umd.js',
                defaultExtension: 'js'
            },
            '@angular/http': {
                main: 'bundles/http.umd.js',
                defaultExtension: 'js'
            },
            '@angular/platform-browser': {
                main: 'bundles/platform-browser.umd.js',
                defaultExtension: 'js'
            },
            '@angular/platform-browser-dynamic': {
                main: 'bundles/platform-browser-dynamic.umd.js',
                defaultExtension: 'js'
            },
            '@angular/router': {
                main: 'bundles/router.umd.js',
                defaultExtension: 'js'
            },
            'rxjs': {
                main: 'Rx.js',
                defaultExtension: 'js'
            },
            'primeng': {
                'defaultExtension': 'js'
            },
            '@swimlane/ngx-charts': { main: 'release/index.min.js', defaultExtension: 'js' },
            'd3-array': { main: 'build/d3-array.min.js', defaultExtension: 'js' },
            'd3-format': { main: 'build/d3-format.min.js', defaultExtension: 'js' },
            'd3-brush': { main: 'build/d3-brush.min.js', defaultExtension: 'js' },
            'd3-color': { main: 'build/d3-color.min.js', defaultExtension: 'js' },
            'd3-force': { main: 'build/d3-force.min.js', defaultExtension: 'js' },
            'd3-hierarchy': { main: 'build/d3-hierarchy.min.js', defaultExtension: 'js' },
            'd3-interpolate': { main: 'build/d3-interpolate.min.js', defaultExtension: 'js' },
            'd3-scale': { main: 'build/d3-scale.min.js', defaultExtension: 'js' },
            'd3-selection': { main: 'build/d3-selection.min.js', defaultExtension: 'js' },
            'd3-shape': { main: 'build/d3-shape.min.js', defaultExtension: 'js' },
            'd3-time-format': { main: 'build/d3-time-format.min.js', defaultExtension: 'js' },
            'd3-drag': { main: 'build/d3-drag.min.js', defaultExtension: 'js' },
            'd3-transition': { main: 'build/d3-transition.min.js', defaultExtension: 'js' },
            'd3-dispatch': { main: 'build/d3-dispatch.min.js', defaultExtension: 'js' },
            'd3-path': { main: 'build/d3-path.min.js', defaultExtension: 'js' },
            'd3-ease': { main: 'build/d3-ease.min.js', defaultExtension: 'js' },
            'd3-timer': { main: 'build/d3-timer.min.js', defaultExtension: 'js' },
            'd3-quadtree': { main: 'build/d3-quadtree.min.js', defaultExtension: 'js' },
            'd3-time': { main: 'build/d3-time.min.js', defaultExtension: 'js' },
            'd3-collection': { main: 'build/d3-collection.min.js', defaultExtension: 'js' }
        }
    };
```

**Comment by zladuric** [comment] 2017-08-21 08:56
@aGoncharuks did I understand correctly that you added stuff to both seed.config and project.config? For me it was only project.config, didn't work when I had it in both places.

**Comment by mgechev** [comment] 2017-08-21 18:27
@zladuric you are not supposed to change `seed.config.ts`. Maybe the issue is related to a property in `seed.config.ts` which is being used as part of your `project.config.ts` and not overridden?

**Comment by zladuric** [comment] 2017-08-21 18:30
Yes, I know, but I was trying various things to make it work. Changing project.config didn't work for me (don't remember the issue), so I ended up modifying seed.config and adding a TODO to do it properly later. Then later I've added stuff to project.config, but forgot to remove seed.config stuff, and it still didn't work, and when I reverted it all the way back, I've finally solved it.

**Comment by zladuric** [comment] 2017-08-22 18:27
@mgechev one question about "not supposed to change seed.config.ts" - I have a private npm package ("@zladuric/ngx-infinite-scroll" as mentioned somewhere, fork of regular ngx-infinite-scroll").

But if I don't include it [here](https://github.com/mgechev/angular-seed/blob/master/tools/config/seed.config.ts#L465) in seed.config, , copying `join('node_modules', '@angular', '*', 'package.json')` line, than `build.prod` fails, because it looks for package.json there?

It fails with:

    originalErr: Error: ENOENT: no such file or directory, open '/home/zlatko/projects/snakt-web/node_modules/@zladuric/package.json'
 
(Going through all this again because I _again_ have silly problems with build.prod.)

**Comment by mgechev** [comment] 2017-08-22 18:57
@zladuric the cleanest way will be to override `SYSTEM_BUILDER_CONFIG` in `project.config.ts`.

You can either override the entire property or just `SYSTEM_BUILDER_CONFIG. packageConfigPaths`.

**Comment by aGoncharuks** [comment] 2017-08-24 09:34
@mgechev can you please take a look at first post in this thread. As far as I understand, all new packages should be added by changing project.config.ts and that's true for HttpClientModule as well. Did I miss anything or did something wrong in any of steps? I just created new branch and repeated all steps, and still have the in console: 
` (SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/@angular/common/http.js. `

**Comment by mgechev** [comment] 2017-08-30 19:52
Closing it because of https://github.com/mgechev/angular-seed/issues/2057.

**Closed by mgechev** 2017-08-30 19:52 UTC

**Comment by TrueGeek** [comment] 2017-10-16 20:13
I know this is a closed item, but I wanted to add that @mgechev's comment helped me:

> the cleanest way will be to override SYSTEM_BUILDER_CONFIG in project.config.ts

The syntax to do this is:

`this.SYSTEM_BUILDER_CONFIG.packageConfigPaths.push(join('node_modules', '@ngx-translate', '*', 'package.json'));
`

**Comment by akshayantony** [comment] 2018-10-11 06:52
This solution worked for me
Adding
'@angular/common/http': 'npm:@angular/common/bundles/common-http.umd.js',
'tslib': 'npm:tslib/tslib.js',
in my systemjs.config file resolved the issue for me.

**Comment by asad-sangla** [comment] 2019-01-23 14:38
> @negberts do it get it right that to get http client working you did the following steps:
> 
> 1. In seed.config.ts:
>    Add this line of code:
>    `'@angular/common/http': 'node_modules/@angular/common/bundles/common-http.umd.js'`
>    to SYSTEM_CONFIG_DEV.paths object and to SYSTEM_BUILDER_CONFIG.paths
> 2. In project.config.ts add this package definition to additionalPackages array:
> 
> ```
> {
>       name: 'tslib',
>       path: 'node_modules/tslib/tslib.js'
> } 
> ```
> 1. In app.module.ts:
>    Add HttpClientModule to IMPORTS array and import the module like this:
>    `import { HttpClientModule } from '@angular/common/http'; `
> 
> And it worked for you with no errors.
> Are there any steps I missed?

'@angular/common/http': 'npm:@angular/common/bundles/common-http.umd.js',
  'tslib': 'npm:tslib/tslib.js'
[angular/angular/issues/18735](https://github.com/angular/angular/issues/18735l)
