### ISSUE TITLE
Build.tools fail

### ISSUE THREAD

**Issue by fvandangeon** [mgechev/angular-seed#1892] opened 2017-04-05 14:37 UTC
**I'm submitting a bug report**

**Current behavior**
When launching the build.tools task I get this error : 
```
[16:26:44] Starting 'build.tools'...
D:\xxx\angular2-seed\node_modules\lodash\lodash.js:494
      case 0: return func.call(thisArg);
                          ^
SyntaxError: Invalid or unexpected token
    at D:\xxx\angular2-seed\node_modules\lodash\lodash.js:14843:16
    at apply (D:\xxx\angular2-seed\node_modules\lodash\lodash.js:494:27)
    at D:\xxx\angular2-seed\node_modules\lodash\lodash.js:15227:16
    at apply (D:\xxx\angular2-seed\node_modules\lodash\lodash.js:496:27)
    at D:\xxx\angular2-seed\node_modules\lodash\lodash.js:6600:16
    at template (D:\xxx\angular2-seed\node_modules\lodash\lodash.js:14842:20)
    at DestroyableTransform._transform (D:\xxx\angular2-seed\node_modules\gulp-template\index.js:20:14)
    at DestroyableTransform.Transform._read (D:\xxx\angular2-seed\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (D:\xxx\angular2-seed\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (D:\xxx\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:345:64)

```

**Expected behavior**
Does this build is still useful ?
I'm on windows environment and a few month ago this build was supposed to speedup building process ... is it still the case?

**Minimal reproduction of the problem with instructions**
Just launch "npm run gulp build.tools" command on the latest master branch

**Please tell us about your environment:**
Windows 10

* **Angular Seed Version:** `23b051`

* **Node:** `node --version` =v6.8.1

**Comment by mgechev** [comment] 2017-04-06 01:47
I'm not using Windows and it'll be hard to confirm. I'd love if anyone with a Windows environment can provide direction.

**Comment by Karasuni** [comment] 2017-04-06 11:57
I'm observing the same issue with `npm run gulp build.tools` but I have never had to run that command before. The speedup as described in the README relies on typescript compilation and not a gulp task.

**Comment by stich6269** [comment] 2017-04-11 19:01
Same issue for me. I have to run build.tools because config.js is not exist by default, and, as result, i have 
`[21:58:35] Starting 'build'...
[21:58:35] Starting 'initialize'...
[21:58:35] Starting 'noop'...
[21:58:35] Finished 'noop' after 96 ms
[21:58:35] Finished 'initialize' after 97 ms
[21:58:35] Starting 'check.tools'...
[21:58:35] Tools not compiled, skipping rebuild
[21:58:35] Finished 'check.tools' after 386 ms
[21:58:35] Starting 'clean.prod'...`

Tools not compiled, skipping rebuild error, so, as I understood, my config file wasn't compiled, so all build setup doesn't work.

**Comment by UrosSimovic** [comment] 2017-04-12 07:56
Maybe related. I'm using `@nglibs/meta` package and when I want to build the project with `npm run build.prod.rollup.aot` I get this:


```
....
[09:06:06] Starting 'build.bundles.app.rollup.aot'...
node_modules\@nglibs\meta\src\meta.guard.js (10:29) 'get' is not exported by 'node_modules\lodash\lodash.js'
node_modules\@nglibs\meta\src\meta.service.js (27:38) 'has' is not exported by 'node_modules\lodash\lodash.js'
node_modules\@nglibs\meta\src\meta.service.js (58:27) 'get' is not exported by 'node_modules\lodash\lodash.js'
node_modules\@nglibs\meta\src\meta.service.js (69:34) 'get' is not exported by 'node_modules\lodash\lodash.js'
node_modules\@nglibs\meta\src\meta.service.js (93:22) 'get' is not exported by 'node_modules\lodash\lodash.js'
node_modules\@nglibs\meta\src\meta.service.js (101:38) 'get' is not exported by 'node_modules\lodash\lodash.js'
node_modules\@nglibs\meta\src\meta.service.js (143:43) 'get' is not exported by 'node_modules\lodash\lodash.js'
node_modules\@nglibs\meta\src\meta.service.js (193:37) 'get' is not exported by 'node_modules\lodash\lodash.js'
[09:06:21] Finished 'build.bundles.app.rollup.aot' after 15 s
[09:06:21] Starting 'transpile.bundles.rollup.aot'...

HIDDEN\node_modules\lodash\lodash.js:494
      case 0: return func.call(thisArg);
                          ^
SyntaxError: Invalid or unexpected token
    at HIDDEN\node_modules\lodash\lodash.js:14843:16
    at apply (HIDDEN\node_modules\lodash\lodash.js:494:27)
    at HIDDEN\node_modules\lodash\lodash.js:15227:16
    at apply (HIDDEN\node_modules\lodash\lodash.js:496:27)
    at HIDDEN\node_modules\lodash\lodash.js:6600:16
    at template (HIDDEN\node_modules\lodash\lodash.js:14842:20)
    at DestroyableTransform._transform (HIDDEN\node_modules\gulp-template\index.js:20:14)
    at DestroyableTransform.Transform._read (HIDDEN\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (HIDDEN\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (HIDDEN\node_modules\readable-stream\lib\_stream_writable.js:345:64)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\HIDDEN\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build.prod.rollup.aot"
npm ERR! node v6.10.0
npm ERR! npm  v3.9.2
npm ERR! code ELIFECYCLE
npm ERR! HIDDEN@0.0.0 build.prod.rollup.aot: `gulp build.prod.rollup.aot --color --env-config prod --build-type prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the HIDDEN@0.0.0 build.prod.rollup.aot script 'gulp build.prod.rollup.aot --color --env-config prod --build-type prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the HIDDEN package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build.prod.rollup.aot --color --env-config prod --build-type prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs HIDDEN
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls HIDDEN
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

**Comment by jakubszlendak** [comment] 2017-04-12 10:42
Same problem when trying to build `npm run build.prod.rollup.aot` when lodash included. It might be related with #1498

**Comment by caolgood** [comment] 2017-04-20 13:59
I'm able to reproduce this on a macbook as well.

It's happening when the stringified build.js.prod.rollup.aot.ts is passed into gulp-template.
It does not happen if i remove the "%"'s from this line
.pipe(plugins.template(new TemplateLocalsBuilder().build(), {interpolate: /<%=([\s\S]+?)%>/g}))

**Comment by lakshmikant4u** [comment] 2017-04-23 11:31
Solution given by @rramo012 in #1498 works.

**Comment by mgechev** [comment] 2017-04-23 18:19
@lakshmikant4u thanks for the comment and sharing your experience! Can we close the issue?

**Comment by lakshmikant4u** [comment] 2017-04-23 18:30
@mgechev Have tried with many ways, current seed 4.0.0 works fine, so I believe we can close this issue. 
I do have css issues for my custom project ( used seed 4.0.0) i,e after bundling font awesome are not applied to template created dynamically e,g when ng-repeat used some custom css are missing in bundle ( like my-fav:before{ content: "\f006"} )

**Closed** 2017-04-23 18:34 UTC

**Comment by Flood** [comment] 2017-05-05 13:38
I guess it should be re-opened. The problem still exists even without the ${ sequence.

Or if we stick to this issue only: https://github.com/mgechev/angular-seed/issues/1498
