### ISSUE TITLE
build.prod.exp failed with error: Error on fetch for dist/tmp/node_modules/@angular/router/src/directives/router_outlet.ngfactor y.js

### ISSUE THREAD

**Issue by agasbzj** [mgechev/angular-seed#1537] opened 2016-10-25 08:36 UTC
Hello:
When doing **npm start** everything works fine but if you do **npm run build.prod.exp**(AOT compile), it fail to pass the compilation. The error message looks like this:
```
[16:19:07] Error on fetch for dist/tmp/node_modules/@angular/router/src/directives/router_outlet.ngfactor
y.js at file:///Volumes/MacintoshHD/Projects/Html5/yd-client/web/node_modules/dist/tmp/node_modules/@angu
lar/router/src/directives/router_outlet.ngfactory.js                                                     
        Loading dist/tmp/app/app.component.ngfactory.js                                                  
        Loading dist/tmp/app/app.module.ngfactory.js                                                     
        Loading dist/tmp/app/main-prod.js                                                                
        Error: ENOENT: no such file or directory, open '/Volumes/MacintoshHD/Projects/Html5/yd-client/web
/node_modules/dist/tmp/node_modules/@angular/router/src/directives/router_outlet.ngfactory.js'           
    at Error (native)                                                                                    
[16:19:07] 'build.prod.exp' errored after 36 s   
```
I find the path is quite strange: 
```
/node_modules/dist/tmp/node_modules/@angular/router/src/directives/router_outlet.ngfactory.js
```
I think the build output path shouldn't be in the node_module dir.

I'm using the latest angular-seed on macOS btw.
I attached the whole solution here to help you reproducing the problem.
[angular-app.zip](https://github.com/mgechev/angular-seed/files/550036/angular-app.zip)
Thanks.

**Comment by koodikindral** [comment] 2016-10-25 13:40
Looks like similar error to: #1523

**Comment by mgechev** [comment] 2016-10-25 16:30
Yes, seems duplicate of #1523. Closing this one and posted a link to the demo.

**Closed by mgechev** 2016-10-25 16:30 UTC
