### ISSUE TITLE
prod build task doesn't compile ts files into one file

### ISSUE THREAD

**Issue by premiumwd** [mgechev/angular-seed#1947] opened 2017-05-26 20:37 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

**Expected behavior**

It creates a js file for each component in dev, in prod none are outputted..

**Minimal reproduction of the problem with instructions**

run gulp build.prod

**What is the motivation / use case for changing the behavior?**

The intended behavior should create one js file.

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

1.0

* **Node:** `node --version` = 7.1

**Comment by mgechev** [comment] 2017-05-26 20:47
Probably the issue is related to malfunctioning fork of the seed. The build is passing and one of the requirements for this is the production build to work successfully.

Closing the issue for now. If it turns out that it's not a support request related to broken configuration I will reopen it and work on the potential issue.

**Closed by mgechev** 2017-05-26 20:47 UTC

**Comment by premiumwd** [comment] 2017-05-26 20:52
H:\angular-seed-master>gulp build.prod
[13:38:17] Requiring external module ts-node/register
[13:38:26] Loading tasks folder H:\angular-seed-master\tools\tasks\seed
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\build.assets
.dev
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\build.assets
.prod
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\build.bundle
.rxjs
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\build.bundle
s.app.aot
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\build.bundle
s.app.rollup.aot
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\build.bundle
s.app
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\build.bundle
s
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\build.docs
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\build.html_c
ss
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\build.index.
dev
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\build.index.
prod
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\build.js.dev

[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\build.js.e2e

[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\build.js.pro
d.aot
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\build.js.pro
d.rollup.aot
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\build.js.pro
d
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\build.js.tes
t
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\build.tools
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\check.tools
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\check.versio
ns
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\clean.all
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\clean.covera
ge
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\clean.dev
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\clean.e2e
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\clean.prod
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\clean.tools
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\clear.files
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\compile.ahea
d.prod
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\copy.prod.ro
llup.aot
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\copy.prod
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\e2e
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\generate.man
ifest
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\i18n.build
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\i18n.merge
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\karma.run
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\karma.run.wi
th_coverage
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\karma.watch
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\minify.bundl
es
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\minify.index

[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\noop
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\print.banner

[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\serve.covera
ge
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\serve.covera
ge.watch
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\serve.docs
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\server.prod
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\server.start

[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\start.deving

[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\sw.manifest.
static
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\transpile.bu
ndles.rollup.aot
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\tslint
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\watch.dev
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\watch.e2e
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\watch.test
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\seed\webdriver
[13:38:26] Loading tasks folder H:\angular-seed-master\tools\tasks\project
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\project\build.ass
ets.dev
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\project\build.ass
ets.prod
[13:38:26] Registering task H:\angular-seed-master\tools\tasks\project\sample.ta
sk
[13:38:26] Using gulpfile H:\angular-seed-master\gulpfile.ts
[13:38:26] Starting 'build.prod'...
[13:38:26] Starting 'initialize'...
[13:38:26] Starting 'noop'...
[13:38:26] Finished 'noop' after 6.7 ms
[13:38:26] Finished 'initialize' after 12 ms
[13:38:26] Starting 'check.tools'...
[13:38:26] Tools not compiled, skipping rebuild
[13:38:26] Finished 'check.tools' after 48 ms
[13:38:26] Starting 'clean.prod'...
[13:38:26] Deleted dist/prod
[13:38:26] Deleted dist/tmp
[13:38:26] Finished 'clean.prod' after 61 ms
[13:38:26] Starting 'tslint'...

ERROR: H:/angular-seed-master/src/client/app.module.ts[44, 2]: file should end w
ith a newline


ERROR: H:/angular-seed-master/src/client/main.ts[35, 5]: file should end with a
newline


ERROR: H:/angular-seed-master/src/client/assets/ts/global/global-const.ts[3, 43]
: file should end with a newline


ERROR: H:/angular-seed-master/src/client/assets/ts/global/globals.ts[6, 3]: file
 should end with a newline
ERROR: H:/angular-seed-master/src/client/assets/ts/global/globals.ts[6, 2]: trai
ling whitespace
ERROR: H:/angular-seed-master/src/client/assets/ts/global/globals.ts[3, 13]: Mis
sing semicolon


ERROR: H:/angular-seed-master/src/client/assets/ts/components/layout/header/head
er.ts[23, 29]: missing whitespace


ERROR: H:/angular-seed-master/src/client/assets/ts/components/layout/header/logo
.ts[11, 27]: missing whitespace


ERROR: H:/angular-seed-master/src/client/assets/ts/components/layout/header/navi
gation.ts[11, 33]: missing whitespace
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[28, 58]: The property "menu" that you're trying to access does not exist in the
 class declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[28, 67]: The property "active" that you're trying to access does not exist in t
he class declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[28, 84]: The method "onSelect" that you're trying to access does not exist in t
he class declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[29, 38]: The property "menu" that you're trying to access does not exist in the
 class declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[30, 25]: The property "menu" that you're trying to access does not exist in the
 class declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[1, 1]: The property "menu" that you're trying to access does not exist in the c
lass declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[1, 1]: The property "menu" that you're trying to access does not exist in the c
lass declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[34, 61]: The property "menu" that you're trying to access does not exist in the
 class declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[34, 70]: The property "dropdown" that you're trying to access does not exist in
 the class declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[34, 79]: The property "menu" that you're trying to access does not exist in the
 class declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[35, 73]: The method "onSelect" that you're trying to access does not exist in t
he class declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[36, 46]: The property "menu" that you're trying to access does not exist in the
 class declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[37, 33]: The property "submenu" that you're trying to access does not exist in
the class declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[1, 1]: The property "menu" that you're trying to access does not exist in the c
lass declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[28, 58]: The property "menu" that you're trying to access does not exist in the
 class declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[28, 67]: The property "active" that you're trying to access does not exist in t
he class declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[28, 84]: The method "onSelect" that you're trying to access does not exist in t
he class declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[29, 38]: The property "menu" that you're trying to access does not exist in the
 class declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[30, 25]: The property "menu" that you're trying to access does not exist in the
 class declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[1, 1]: The property "menu" that you're trying to access does not exist in the c
lass declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[1, 1]: The property "menu" that you're trying to access does not exist in the c
lass declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[34, 61]: The property "menu" that you're trying to access does not exist in the
 class declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[34, 70]: The property "dropdown" that you're trying to access does not exist in
 the class declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[34, 79]: The property "menu" that you're trying to access does not exist in the
 class declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[35, 73]: The method "onSelect" that you're trying to access does not exist in t
he class declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[36, 46]: The property "menu" that you're trying to access does not exist in the
 class declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[37, 33]: The property "submenu" that you're trying to access does not exist in
the class declaration.
ERROR: H:/angular-seed-master/src/client/templates/global/header/navigation.html
[1, 1]: The property "menu" that you're trying to access does not exist in the c
lass declaration.


ERROR: H:/angular-seed-master/src/client/assets/ts/components/layout/footer/foot
er.ts[10, 29]: missing whitespace


ERROR: H:/angular-seed-master/src/client/assets/ts/components/layout/footer/navi
gation.ts[10, 39]: missing whitespace


ERROR: H:/angular-seed-master/tools/config/project.config.ts[27, 1]: trailing wh
itespace
ERROR: H:/angular-seed-master/tools/config/project.config.ts[37, 1]: trailing wh
itespace
ERROR: H:/angular-seed-master/tools/config/project.config.ts[39, 85]: trailing w
hitespace
ERROR: H:/angular-seed-master/tools/config/project.config.ts[40, 85]: trailing w
hitespace


ERROR: H:/angular-seed-master/tools/config/seed.config.ts[190, 1]: trailing whit
espace


ERROR: H:/angular-seed-master/tools/tasks/project/build.assets.dev.ts[26, 5]: fi
le should end with a newline
ERROR: H:/angular-seed-master/tools/tasks/project/build.assets.dev.ts[19, 65]: t
railing whitespace

[13:38:33] Finished 'tslint' after 6.35 s
[13:38:33] Starting 'build.assets.prod'...
[13:38:34] Finished 'build.assets.prod' after 1.57 s
[13:38:34] Starting 'build.html_css'...
Node#moveTo was deprecated. Use Container#append.
[13:38:58] Finished 'build.html_css' after 23 s
[13:38:58] Starting 'copy.prod'...
[13:38:58] Finished 'copy.prod' after 680 ms
[13:38:58] Starting 'build.js.prod'...
Error: ENOENT: no such file or directory, open 'H:\angular-seed-master\dist\tmp\
templates\global\body.html'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at getFileData (H:\angular-seed-master\node_modules\gulp-inline-ng2-template
\parser.js:284:17)
    at H:\angular-seed-master\node_modules\gulp-inline-ng2-template\parser.js:24
8:22
    at H:\angular-seed-master\node_modules\async\dist\async.js:3830:24
    at replenish (H:\angular-seed-master\node_modules\async\dist\async.js:946:17
)
    at H:\angular-seed-master\node_modules\async\dist\async.js:950:9
    at eachOfLimit (H:\angular-seed-master\node_modules\async\dist\async.js:975:
24)
    at H:\angular-seed-master\node_modules\async\dist\async.js:980:16
    at _parallel (H:\angular-seed-master\node_modules\async\dist\async.js:3829:5
)

H:\angular-seed-master>

**Comment by mgechev** [comment] 2017-05-26 20:53
```
Error: ENOENT: no such file or directory, open 'H:\angular-seed-master\dist\tmp
templates\global\body.html'
at Object.fs.openSync (fs.js:584:18)
at Object.fs.readFileSync (fs.js:491:33)
at getFileData (H:\angular-seed-master\node_modules\gulp-inline-ng2-template
\parser.js:284:17)
at H:\angular-seed-master\node_modules\gulp-inline-ng2-template\parser.js:24
8:22
at H:\angular-seed-master\node_modules\async\dist\async.js:3830:24
at replenish (H:\angular-seed-master\node_modules\async\dist\async.js:946:17
)
at H:\angular-seed-master\node_modules\async\dist\async.js:950:9
at eachOfLimit (H:\angular-seed-master\node_modules\async\dist\async.js:975:
24)
at H:\angular-seed-master\node_modules\async\dist\async.js:980:16
at _parallel (H:\angular-seed-master\node_modules\async\dist\async.js:3829:5
)
```

Looks like an issue in the fork. Maybe you've missed `module.id`.

**Comment by premiumwd** [comment] 2017-05-26 20:58
All my components, modules have module.id

@Component({
  moduleId: module.id,
  selector: 'phx-body',
  templateUrl: '../../../../../templates/global/body.html',
})
