### ISSUE TITLE
Cannot easily update computed config members in ProjectConfig

### ISSUE THREAD

**Issue by tvrtkos** [mgechev/angular-seed#823] opened 2016-05-06 14:54 UTC
If you set APP_SRC inside ProjectConfig you don't get .css files injected into index.html.

I guess the reason is that properties like CSS_SRC and APP_ASSETS are calculated using old/default value of APP_SRC.

I can change APP_SRC inside SeedConfig as a workaround.

**Comment by mgechev** [comment] 2016-05-08 02:17
Yes, this is an issue discussed before. I guess a way to handle is by using property accessors instead.

If you have some spare time, a PR is welcome!

**Comment by d3viant0ne** [comment] 2016-05-08 02:44
@mgechev - I'm working on the manual_typings problem, I can roll this into that PR unless @tvrtkos wants to take this one.

If I don't see anything by the time I finish with the typings, i'll fix this in the PR for that

**Comment by Paladinium** [comment] 2016-05-11 04:59
Same issue as #630 

@tvrtkos : you'll see the workaround there which is just overriding all dependent variables.

**Comment by ludohenin** [comment] 2016-05-21 12:13
@d3viant0ne Are you working on that one, or can I take over ?

**Comment by mgechev** [comment] 2016-05-29 11:15
Any updates here? I can take it as well.

**Comment by mgechev** [comment] 2016-10-25 17:52
Duplicate of https://github.com/mgechev/angular-seed/issues/1429

**Closed by mgechev** 2016-10-25 17:52 UTC
Labels: enhancement
