### ISSUE TITLE
Error: Unexpected token <, while importing primeng components

### ISSUE THREAD

**Issue by salauddinShaikh** [mgechev/angular-seed#1959] opened 2017-06-08 10:29 UTC

**Comment by siovene** [comment] 2017-06-08 10:57
I'm seen that when using `require` to import `hterm-umdjs`, and I observed that something injected my `index.html` code into the `index.ts` file of `hterm-umdjs`. Using `systemjs` to do the import fixed the issue for me.

**Comment by chetanbadgujar9** [comment] 2017-06-08 11:05
@siovene Sry to say but I am not getting ur point. Can u plz elaborate?? thanks in advance

**Comment by siovene** [comment] 2017-06-08 11:28
@chetanbadgujar9 well it's hard to guess what the reported meant given the lack of details, but in my angular-seed based project I use [hterm-umdjs](https://github.com/dbkaplun/hterm-umdjs) and if import it using `require` then I get that "Unexpected token <" error.

If I inspect with the Chrome developer tools, I see that the contents of the file I was trying to import (`node_modules/hterm-umdjs/dist/index.js`) were mangled with the contents of my `src/client/index.html`.

So something in the build process (I suppose) messed that up. I really didn't investigate, because I changed my import from `require('hterm-umdjs'` to  `import { hterm, lib } from 'hterm-umdjs';}.

Obviously this is not directly applicable to the reporter's problem, because he or she is trying to import something else. But perhaps the root cause is the same?

Might actually be a bug in the gulp tasks of this project.

**Comment by MarcAragones** [comment] 2017-06-08 14:30
I get the same error while following the [Add external dependency wiki](https://github.com/mgechev/angular-seed/wiki/Add-external-dependency):

> SyntaxError: Unexpected token <
>    at eval (<anonymous>)
>    at evaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1496931996294:2843:16)
>    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1496931996294:3643:21
>    ...

Before the SystemJS update, everything worked fine.

**Comment by mgechev** [comment] 2017-06-08 16:55
Most likely it's caused by the SystemJS update. You can revert back to [this version of the seed](https://github.com/mgechev/angular-seed/commit/158c3889a3b868051a321040e2427198c033e14d) until the issue is resolved.

**Comment by premiumwd** [comment] 2017-06-08 17:20
please give us version of systemjs, link doesn't say anything just contributors.

**Comment by siovene** [comment] 2017-06-08 19:00
Yes, I can confirm that I started seeing the issue after the SystemJS update.

**Comment by chetanbadgujar9** [comment] 2017-06-09 07:30
@mgechev : can u plz send the link of previous version of the seed project so I can clone the repo. thanx in advance

**Comment by chetanbadgujar9** [comment] 2017-06-09 09:54
@mgechev : I have reverted back to previous versions like 2.1.2, 2.0,1, 2.0.0 but getting the same error.

**Comment by reigelj** [comment] 2017-06-09 16:51
I had this issue as well when trying to use primeng. For me, the issue was resolved by adding primeng to the system_config_dev packages in seed.config.ts. 
`  SYSTEM_CONFIG_DEV: any = {
    paths: {
    ...
    packages:{
    ...
      primeng: {
        defaultExtension: 'js'
      }
    ` 
I am not sure if the primeng wiki should be updated, or if this is just a workaround caused by some other issue. At any rate, I hope it helps!

**Comment by salauddinShaikh** [comment] 2017-06-10 04:35
Thanks @mgechev, issue resolved by reverting to previous version.

**Comment by oMinGWo** [comment] 2017-06-15 12:39
@salauddinShaikh hey, could plz tell me what's your systemjs version when everything is ok?

**Comment by brian428** [comment] 2017-06-15 15:12
When using PrimeNG, I was able to get it to work with some trial and error. Basically, your SystemJS config needs to look something like this:

```
{
  "paths": {
    "app/main": "/app/main",
    "": "node_modules/",
    ...other paths...
    "primeng": "node_modules/primeng"
  },
  "packages": {
    "app": {
      "defaultExtension": "js"
    },
    "primeng": {
      "defaultExtension": "js"
    }
  }
}
```

I'm sure there's a way to do this using the built-in `addPackageBundles()` or `addPackagesBundles()` methods in `SeedConfig`. I created my own helper methods to do this a long time back and never got around to changing my `ProjectConfig` to use the built-in methods, so you may have to try it out yourself. But the basic point is that I believe you need a `primeng` path and a `primeng` package configuration.

**Comment by reigelj** [comment] 2017-06-15 15:23
Thanks @brian428! I really appreciate it. I knew I was missing something since my workaround was so tedious. I should have checked the methods more.

**Comment by treyrich** [comment] 2017-06-15 15:45
Just want to throw my voice in here. The SystemJS update definitely threw my project for a loop, most of the packages I was adding via`addPackageBundles` were broken, and many of the packages that I previously didn't need to include in the config, now were required. I spent about 1.5 hrs yesterday trying to get everything to build properly without luck, so I reverted SystemJS to fight again another day.

I'm sure the issues experienced here are probably easily resolved once they're understood, but I wonder if a migration guide is needed? At the very least I think all of the wiki pages instructing how to add third party libraries will need to be updated.

I'll update here with the solutions I end up using once I get around to actually figuring things out, unless someone else has already posted a viable migration path for existing projects.

**Comment by brian428** [comment] 2017-06-15 16:25
Maybe we could even implore Minko to write a blog entry about SystemJS in detail. I still have only a very vague understanding of the difference between paths, maps, and packages. They all seem to overlap a lot. Same with the SystemJS config vs. the SystemJS Builder config.

I've tried to read the SystemJS config API docs, and they're rather hard to decipher. I get that SystemJS is fairly complex because it has to handle a lot of different JS module types. But instead of just explaining what something actually does, they reference back and forth inside the docs themselves. So you're left jumping all over the place just trying to answer a basic question like "what the heck is the difference between a path and a package".

**Comment by treyrich** [comment] 2017-06-15 23:42
It seems that part of the problem (that I'm having at least) derives from SystemJS no longer implicitly searching node_modules for imports, which means that every external package that needs to be imported must be listed in the config. Is that correct @mgechev? If so, I think that calls into question another issue that third party libraries will have in that many assume that they can import dependencies without stating `node_modules` in the import. I just spent about an hour trying to chase down a single project dependency, and eventually it became apparent that it wouldn't be possible simply by using the `addPackageBundles` method. I haven't yet dug into the specifics of what needs to change in the SystemJS config, but I think something definitely does need to change.

**Comment by brian428** [comment] 2017-06-19 19:08
I'd add that one frustrating side-effect of the SystemJS update is that when some dependency can't be found, it seems to default to just trying to include the root `index.html` file. When you see the `unexpected token <`, this is due to SystemJS trying to parse the HTML as JSON/JS, and blowing up on the initial tag.

I wonder if there's some way to prevent this, so that when it can't find something, it actually tells you what it can't find instead of spitting out the misleading `unexpected token <` error.

**Comment by mgechev** [comment] 2017-07-16 10:28
Closing this issue since it's related to misconfiguration of SystemJS.

**Closed by mgechev** 2017-07-16 10:28 UTC

**Comment by hhubik** [comment] 2017-07-21 03:25
@brian428 - thanks for the suggestion and inspiration.  I was struggling with this since I had updated my app to the current Seed last week.  After reading your posts, I have got the PrimeNG library to work under SystemJS 0.20.14 by including the following code in my `project.config.ts':
```
    let additionalPackages: ExtendPackages[] = [{
      name: 'primeng',
      path: 'node_modules/primeng',
      packageMeta: {
        defaultExtension: 'js'
      }
    }
       }
  ];

    this.addPackagesBundles(additionalPackages);
```
I also had to do the same thing for a bunch of other third-party libraries that had also stopped working after the Seed update.

**Comment by chaisangam** [comment] 2017-11-22 19:42
I had the same issue and when I updated my systemjs.config.js to include primeng like 
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      'app': '/src/app',

        // angular bundles
      '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js',      
      'primeng': "npm:primeng"
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
        app: {
            defaultExtension: 'js',
            meta: {
                './*.js': {
                    loader: '/src/systemjs-angular-loader.js'
                }
            }
        },
        "primeng": {
          "defaultExtension": "js"
        }
    }
  });

It worked fine.
