### ISSUE TITLE
serve.dev via https

### ISSUE THREAD

**Issue by g-schmitz** [mgechev/angular-seed#2012] opened 2017-07-11 13:45 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Currently the seed is served thru http.

**Expected behavior**
To access some features (e.g. MediaDevices) the app has to be served thru https, so that for ex. mobile phones can use those features the via the running dev instance.

**Comment by mgechev** [comment] 2017-07-11 15:55
Here's a way to approach:

- With flags pass path to the certificate and run browsersync in TLS mode.

@g-schmitz would you want to open a PR? The issue is low priority so, unfortunately, it's not something I'll be able to start working on in near future.

**Comment by ZuSe** [comment] 2017-07-16 08:32
Just for the ones that need a quick solution:
Use something like local-ssl-proxy in the meantime.
https://www.npmjs.com/package/local-ssl-proxy

**Comment by mgechev** [comment] 2017-07-26 09:26
Lets close the issue for now. `local-ssl-proxy` seems reasonable for dev purposes.

**Closed by mgechev** 2017-07-26 09:26 UTC
Labels: enhancement, first timers, help wanted, P3
