### ISSUE TITLE
Use APP_BASE in ngsw-manifest.json

### ISSUE THREAD

**Issue by Hirse** [mgechev/angular-seed#1918] opened 2017-05-03 10:25 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

When using an `APP_BASE` the generated `ngsw-manifest.json` file points to the wrong file locations.
When turning on the Service Worker later, it is unable to find the files and keeps producing 404s.

**Expected behavior**

The file-urls in the `ngsw-manifest.json` should be prefixed with the `APP_BASE`.

**Minimal reproduction of the problem with instructions**

Run `npm run build.dev` on https://github.com/Hirse/angular-seed/tree/app-base.

**What is the motivation / use case for changing the behavior?**

I would like to be able to use the app base and ngsw features.

**Please tell us about your environment:**

* **Angular Seed Version:** `0bac91b6473118d51ac5c28befc221ebeb162f72`

* **Node:** `node --version` = v7.9.0

**Comment by mgechev** [comment] 2017-05-03 16:53
@treyrich would you want to take this?

**Comment by treyrich** [comment] 2017-05-03 17:43
Possibly...The real question I guess is whether this should be passed upstream to [angular/mobile-toolkit](https://github.com/angular/mobile-toolkit). It would be a matter of adding an option to `GulpAddStaticFileOptions` for a base url, then modifying [Line 50](https://github.com/angular/mobile-toolkit/blob/master/service-worker/worker/src/build/gulp.ts#L50) to support the new base URL option.

The problem is that [angular/mobile-toolkit](https://github.com/angular/mobile-toolkit) seems uninterested in pull requests, and just generally opposed to community input at this point. An alternative would be to have [mgechev/angular-seed](https://github.com/mgechev/angular-seed) maintain its own Gulp task to generate the `ngsw-manifest.json` file, but I'm not sure that it's within the scope of the project.

I'm happy to consult on this, or add a PR if needed, but ultimately I don't see a great way forward. Personally I've temporarily suspended use of [angular/mobile-toolkit](https://github.com/angular/mobile-toolkit) and written my own service worker code because of the lack of movement on the project.

**Comment by alxhub** [comment] 2017-05-03 18:38
angular/mobile-toolkit is definitely still in active development, and not at all opposed to community input. Unfortunately I'm the only engineer working on the project and my time is very limited. There has still been plenty of recent progress (e.g. dynamic content caching which landed recently), but you are correct that the PR/issue queues are in need of attention. Part of this is the lack of a stable CI setup, which would make triaging PRs a lot easier (currently it is a manual process).

There is good news though - I'm working on a plan to migrate `@angular/service-worker` into angular/angular itself, at which point it would be using the real Angular CI setup, participate in our triage processes, etc.

**Comment by treyrich** [comment] 2017-05-03 19:20
@alxhub thanks for the comment! I didn't mean any offense about the project, or to imply that it wasn't being actively maintained, just that I personally became disenchanted with contributing to the project due to the apparent lack of interest in my PRs and issues, in particular with regards to push notifications. (This probably isn't the best venue to discuss this, so I apologize for the long winded response)

Circling back to the issue at hand, what's your opinion on this? To me it feels like a simple fix on `@angular/service-worker` like I described to alter the gulp task. Or possibly add the ability to add a base url to the `ngsw-manifest.json` and have this handled dynamically within the routing plugin, though there'd probably have to be an additional use-case for that like keeping things within the correct scope (similar to [this issue](https://github.com/angular/mobile-toolkit/issues/135)).

**Closed** 2017-05-26 19:05 UTC
Labels: bug, P2

**Comment by Hirse** [comment] 2017-05-30 13:26
@mgechev Using the latest commit of Angular Seed this is not resolved.
See my updated branch: https://github.com/Hirse/angular-seed/tree/app-base

**Comment by mgechev** [comment] 2017-05-30 13:44
Yes, this issue seems in the scope of the mobile-toolkit (Alex and @treyrich can correct me if I am wrong).

**Comment by Hirse** [comment] 2017-05-30 13:56
I understand, but given @alxhub's workload is there a possibility to get a quick workaround like modifying the generated `ngsw-manifest.json` in the gulp task?
I have tried to do some modifications, but failed due to my limited (or non-existent) gulp-skills.
