### ISSUE TITLE
endpoints with "." not working

### ISSUE THREAD

**Issue by Perezmarc** [mgechev/angular-seed#1269] opened 2016-08-31 07:54 UTC
**Steps to reproduce and a minimal demo of the problem**
http://localhost:5555/users/a.b

Want to access there. "a.b" is a username, but all I get is:

```
<html><head></head>
<body>Cannot GET /users/a.b
</body></html>
```

Any endpoint having a user without a "." char is working perfectly.

My Routes: 

```
export const routes: Routes = [
  { path: '', redirectTo: 'home', pathMatch: 'full', canActivate: [AuthGuard] },
  { path: 'login', component: LoginComponent },
  { path: 'home', component: HomeComponent, canActivate: [AuthGuard] },
  { path: 'discover', component: DiscoverComponent, canActivate: [AuthGuard] },
  { path: 'profile', component: ProfileComponent, canActivate: [AuthGuard] },
  { path: 'settings', component: SettingsComponent, canActivate: [AuthGuard] },
  { path: 'users', children: [
    {path: ':username', component: ProfileComponent, canActivate: [AuthChecker]}
  ]},
];
```

Thanks!

**Comment by mgechev** [comment] 2016-08-31 16:51
This is not an issue in angular2-seed. We're using the standard Angular 2 router. For further information take a look at the official [Angular 2 repo](https://github.com/angular/angular).

**Comment by Perezmarc** [comment] 2016-09-01 06:52
I'm using angular 2 router...

```
import { RouterModule } from '@angular/router';

@NgModule ( {
  imports: [CommonModule, BrowserModule, HttpModule, RouterModule.forRoot ( routes ), HomeModule, LoginModule,
    DiscoverModule, ProfileModule, SettingsModule, SharedModule.forRoot (),
```

This is the way I import it, 

version: "@angular/router": "3.0.0-beta.2",

**Comment by Perezmarc** [comment] 2016-09-01 06:59
For the record: I discovered is a grunt configuration issue, with the compiled version works as desired

**Comment by mgechev** [comment] 2016-09-01 18:31
In such case it's the seed :-). If you find the root cause, it'll be great if you can open a PR!

**Comment by Perezmarc** [comment] 2016-09-02 10:54
I would like to show some light to the issue, I have too much work to do yet before we release 😞 , need to focus... I don't need it in development, as long as it works good in production don't have the need to solve it 😃 .

**Comment by sasikumardr** [comment] 2016-09-07 16:46
@mgechev This issue is related to browser-sync library. More specifically "connect-history-api-fallback" middleware configured in PLUGIN_CONFIGS (seed.config.ts). "connect-history-api-fallback" treats urls with dots as static resource. This such cases, angular will not come into picture as static-server will try to serve this file directly.

In latest version of library (>=1.3) we have option to disable dot checking in url. But configuring this will cause issues with loading app specific js files.

**Comment by sasikumardr** [comment] 2016-09-14 02:29
@mgechev this issue still there?

**Comment by mgechev** [comment] 2016-09-14 02:40
Yes, there was an issue with the content-type returned by the server (take a look here https://github.com/mgechev/angular2-seed/issues/1332). Doesn't seem like a problem in the `rewrites` that you set looks like something else but didn't have time to debug further.

**Comment by sasikumardr** [comment] 2016-09-14 02:43
I have tested all static files to serving right before committing change. I'll take look into that issue.

**Comment by mgechev** [comment] 2016-09-14 02:46
I was able to reproduce it too, the files are served but `main.css?TIMESTAMP` doesn't get interpreted as `text/css` and the value of the `Content-type` header is `text/html`.

**Comment by sasikumardr** [comment] 2016-09-14 02:48
I can  think of one possibility of  not updating connect-history-api-fallback to 1.3. I'll test again when I get back at office.

**Comment by sasikumardr** [comment] 2016-09-14 03:15
Found the issue. Problem was in checking css directory in rewrite rule. css file was referring from /dist/dev/css. directory. In rewrite rules, i was checking for just /css/. 

Added the fix in my fork and working as expected. I found that you have removed rewrite rules from this repo. So we are dropping this logic now?

**Comment by mgechev** [comment] 2016-09-14 03:24
Would you use the inlined `rewrites` (they are easier for overwrite by `getPluginConfig`) and open a PR?

**Comment by sasikumardr** [comment] 2016-09-14 16:56
Is it right to use dist/dev path for css file in index.html? considering assets and app folders are transformed (by removing dist/dev), shouldn't we do same for css folder also?

**Comment by mgechev** [comment] 2016-09-14 17:46
Yes, it'll be better to transform the url of the CSS file too, in terms of consistency.

Also:

```ts
[
  {
    from: /^\/node_modules\/.*$/,
    to: (context:any) => context.parsedUrl.pathname
  },
  {
    from: /^\/app\/.*$/,
    to: (context:any) => context.parsedUrl.pathname
  },
  {
    from: /^\/assets\/.*$/,
    to: (context:any) => context.parsedUrl.pathname
  },
  {
    from: /^\/css\/.*$/,
    to: (context:any) => context.parsedUrl.pathname
  }
]
```

Will be better if inside the regular expressions we assign to the `from` properties to use the constants defined in the file above (for instance `BOOTSTRAP_DIR`, instead of `app`, etc.). This may require slight change in the constants: `ASSETS_SRC` and `CSS_SRC`.

**Comment by mgechev** [comment] 2016-09-15 23:27
Fixed by https://github.com/mgechev/angular2-seed/commit/0069fda30fd383da96a034a178cbd422fc53bd10.

**Comment by mgechev** [comment] 2016-09-22 18:32
It doesn't seem to have a good fix for this issue which doesn't break anything else.

> @sasikumardr there were a couple of issues with this fix:

> - The rewrites are fixed so when you add a new directory you have to add it by hand.
> - If you generate the rewrites on server start it still can get tricky when you add new files and directories ([here's an](https://github.com/mgechev/angular2-seed/tree/dev-server) experiment).

> I thought about generating only a flat list of directories which are inside `src/client` but still we can't handle 404 properly.

> Basically I think the drawbacks for having the history api fallback failing for URLs with dots are less compared to the ones we get with the rewrites.

**Comment by sasikumardr** [comment] 2016-09-23 04:56
I did not fully understand issue here. But as you mentioned if the fix impacted other useful features, it will be better to revert the commit. 
Only thing we have to note here is that, css folder mapping is changed from /dist/dev/css to /css. (inside build.index.dev), that mapping has to be taken care.

**Comment by sasikumardr** [comment] 2016-10-09 16:45
@mgechev How about we enable rewrites for files with known extensions(configurable in seed.config) like js, css, map, html, jpg, png ... Also some flag like enableDottedRoutes in seed.config to activate this rewrite (by default we will disable rewrite as it is not required for most people)

**Comment by mgechev** [comment] 2016-10-09 19:24
This should be fine. We can have `enableDottedRoutes` in `plugin-config`, this way we won't pollute the interface of the configuration object.

**Comment by sasikumardr** [comment] 2016-10-10 11:32
@mgechev how about this fix? If okay, i can create a PR. 

Reference for regex: http://stackoverflow.com/questions/18086473/regular-expression-for-extension-of-file.

```
 /**
   * Configuration for enabling Angular Routes with dots in it.
   * If this field is configured as true, KNOWN_EXTENSIONS field needs to be customized 
   * in order to render static files.
   */
  ENABLE_DOTTED_ROUTES = false;

  /**
   * Static file extensions seperated by '|'. This will be used in browser-sync middleware to identify static files.
   * To be used in combination with ENABLE_DOTTED_ROUTES = true
   */
  KNOWN_EXTENSIONS = 'js|css|html|ts|json|svg';
  /**
   * Configurations for NPM module configurations. Add to or override in project.config.ts.
   * If you like, use the mergeObject() method to assist with this.
   */
  PLUGIN_CONFIGS: any = {
    /**
     * The BrowserSync configuration of the application.
     * The default open behavior is to open the browser. To prevent the browser from opening use the `--b`  flag when
     * running `npm start` (tested with serve.dev).
     * Example: `npm start -- --b`
     * @type {any}
     */
    'browser-sync': {
      middleware: [require('connect-history-api-fallback')({
        index: `${this.APP_BASE}index.html`,
        rewrites: !this.ENABLE_DOTTED_ROUTES ? [] : [
          {
            from: new RegExp(`^(.*\.(?!(${this.KNOWN_EXTENSIONS})$))?[^.]*$`, 'i'),
            to: (context:any) => context.parsedUrl.pathname
          }
        ],
        disableDotRule: this.ENABLE_DOTTED_ROUTES
      })],
      port: this.PORT,
      ...
   }
```

**Comment by mgechev** [comment] 2016-10-10 17:34
@sasikumardr yep, this makes sense, maybe we can also drop `ENABLE_DOTTED_ROUTES` and add more complete list of extensions? Some [subset of these](http://www.file-extensions.org/filetype/extension/name/internet-related-files/sortBy/extension/order/asc/page/1) looks fine to me.

**Comment by mgechev** [comment] 2017-07-26 10:03
Closing it due to inactivity.

**Closed** 2017-07-26 10:03 UTC
Labels: bug, help wanted, P3
