### ISSUE TITLE
AOT error after updating to latest seed

### ISSUE THREAD

**Issue by sfabriece** [mgechev/angular-seed#1561] opened 2016-10-30 03:22 UTC
**I'm submitting a ...**  (check one with "x")

```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

can't build the AOT version of the app

**Please tell us about your environment:**

- **Angular Seed Version:** 2.1.X
  
  
- **Node:** `node --version` = 7.0.0
- **Output from console:**

``` bash
[04:16:17] Starting 'build.js.prod.exp'...
[04:16:41] Finished 'build.js.prod.exp' after 25 s
[04:16:41] Starting 'build.bundles'...
[04:16:42] Finished 'build.bundles' after 1.09 s
[04:16:42] Starting 'build.bundles.app.exp'...
[04:16:56] 'build.bundles.app.exp' errored after 14 s
[04:16:56] Error on fetch for dist/tmp/node_modules/@angular/common/src/directives/ng_if.ngfactory.js at file:///C:/Users/fabriece/documents/Github/hapi/Orange/node_modules/dist/tmp/node_modules/@angular/common/src/directives/ng_if.ngfactory.js
        Loading dist\tmp\app\webapp/common/common-dialog/commondialog.component.ngfactory.js
        Loading dist\tmp\app\app.module.ngfactory.js
        Loading dist\tmp\app\main-prod.js
        Error: ENOENT: no such file or directory, open 'C:\Users\fabriece\documents\Github\hapi\Orange\node_modules\dist\tmp\node_modules\@angular\common\src\directives\ng_if.ngfactory.js'
[04:16:56] 'build.prod.exp' errored after 2.37 min
[04:16:56] Error in plugin 'run-sequence(build.bundles.app.exp)'
Message:
    Error on fetch for dist/tmp/node_modules/@angular/common/src/directives/ng_if.ngfactory.js at file:///C:/Users/fabriece/documents/Github/hapi/Orange/node_modules/dist/tmp/node_modules/@angular/common/src/directives/ng_if.ngfactory.js
        Loading dist\tmp\app\webapp/common/common-dialog/commondialog.component.ngfactory.js
        Loading dist\tmp\app\app.module.ngfactory.js
        Loading dist\tmp\app\main-prod.js
        ENOENT: no such file or directory, open 'C:\Users\fabriece\documents\Github\hapi\Orange\node_modules\dist\tmp\node_modules\@angular\common\src\directives\ng_if.ngfactory.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open 'C:\Users\fabriece\documents\Github\hapi\Orange\node_modules\dist\tmp\node_modules\@angular\common\src\directives\ng_if.ngfactory.js'
Stack:
Error on fetch for dist/tmp/node_modules/@angular/common/src/directives/ng_if.ngfactory.js at file:///C:/Users/fabriece/documents/Github/hapi/Orange/node_modules/dist/tmp/node_modules/@angular/common/src/directives/ng_if.ngfactory.js
        Loading dist\tmp\app\webapp/common/common-dialog/commondialog.component.ngfactory.js
        Loading dist\tmp\app\app.module.ngfactory.js
        Loading dist\tmp\app\main-prod.js
        Error: ENOENT: no such file or directory, open 'C:\Users\fabriece\documents\Github\hapi\Orange\node_modules\dist\tmp\node_modules\@angular\common\src\directives\ng_if.ngfactory.js'

```

**Comment by RoxKilly** [comment] 2016-10-30 17:18
Looks like the [error seen here](https://github.com/DeviantJS/angular2-seed-material2/issues/72#issuecomment-255593215).  Did you modify any of the task scripts or build your app from a forked version of this repo?

**Comment by felipequiroz** [comment] 2016-10-30 20:14
Hi @RoxKilly 
I have cloned the repo and then compiled:

npm run build.dev --> OK
npm run build.prod --> OK
npm run build.prod.exp --> Error:

`[17:05:24] Starting 'compile.ahead.prod'...
Error: undefined, resolving symbol ApplicationModule in /Users/Quiroz/Development/Virtualab/iSlides/fquiroz-white-2.0/node_modules/@angular/core/src/application_module.d.ts
    at simplifyInContext (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:532:15)
    at StaticReflector.simplify (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:536:20)
    at StaticReflector.annotations (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:93:28)
    at NgModuleResolver.resolve (/Users/Quiroz/Development/Virtualab/iSlides/fquiroz-white-2.0/node_modules/@angular/compiler/bundles/compiler.umd.js:14050:46)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/Quiroz/Development/Virtualab/iSlides/fquiroz-white-2.0/node_modules/@angular/compiler/bundles/compiler.umd.js:14296:49)
    at /Users/Quiroz/Development/Virtualab/iSlides/fquiroz-white-2.0/node_modules/@angular/compiler/bundles/compiler.umd.js:13284:43
    at Array.forEach (native)
    at _extractModulesAndPipesOrDirectives (/Users/Quiroz/Development/Virtualab/iSlides/fquiroz-white-2.0/node_modules/@angular/compiler/bundles/compiler.umd.js:13283:28)
    at analyzeNgModules (/Users/Quiroz/Development/Virtualab/iSlides/fquiroz-white-2.0/node_modules/@angular/compiler/bundles/compiler.umd.js:13039:16)
    at OfflineCompiler.compileModules (/Users/Quiroz/Development/Virtualab/iSlides/fquiroz-white-2.0/node_modules/@angular/compiler/bundles/compiler.umd.js:13115:20)
Compilation failed`

**Comment by RoxKilly** [comment] 2016-10-30 22:39
@felipequiroz this is not the same error from the original post. Please don't conflate multiple issues on the same thread.

**Comment by webia1** [comment] 2016-10-31 16:30
Did yo follow the steps [here](https://www.barbarianmeetscoding.com/blog/2016/08/13/updating-your-angular-2-app-from-rc4-to-rc5-a-practical-guide/) before?

**Comment by mgechev** [comment] 2016-10-31 18:54
Tried to reproduce the issue with the latest master but I wasn't able to. Judging from the error message you're missing `SYSTEM_BUILDER_CONFIG` property. Take a look at the updated config [here](https://github.com/mgechev/angular-seed/blob/master/tools/config/seed.config.ts#L395).

**Closed by mgechev** 2016-10-31 18:54 UTC
